### ISSUE TITLE
feedDiasp.feedDiasp.Diasp.LoginException: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ghost** [fourier/rss-bot-diasp#1]
Hi,

The following error while using the --update option:

```
$ ./rss_bot.py --update jdh
Login as journalduhacker@framasphere.org to https://framasphere.org/
Failed to login: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "./rss_bot.py", line 105, in <module>
    main()
  File "./rss_bot.py", line 101, in main
    bot.publish()
  File "/home/chaica/progra/python/rss-bot-diasp/feedDiasp/feedDiasp/FeedDiasp.py", line 52, in publish
    self.diasp.login()
  File "/home/chaica/progra/python/rss-bot-diasp/feedDiasp/feedDiasp/Diasp.py", line 20, in login
    raise LoginException(str(e))
feedDiasp.feedDiasp.Diasp.LoginException: 'NoneType' object has no attribute 'group'
```

Let me know if you need more information.

Regards,
Carl Chenet

**Comment by fourier** [comment]
Thank you for the report. Are you sure you has entered login credentials correctly? Second question, what version of diaspora are you running? I'm still running 0.4 and this probably a problem.

**Comment by schiessle** [comment]
I have exactly the same problem publishing to diasp.eu

```
Login as schiesbn to https://diasp.eu
Failed to login: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "./rss_bot.py", line 105, in <module>
    main()
  File "./rss_bot.py", line 101, in main
    bot.publish()
  File "/home/schiesbn/bin/diaspora/rss-bot-diasp/feedDiasp/feedDiasp/FeedDiasp.py", line 52, in publish
    self.diasp.login()
  File "/home/schiesbn/bin/diaspora/rss-bot-diasp/feedDiasp/feedDiasp/Diasp.py", line 20, in login
    raise LoginException(str(e))
feedDiasp.feedDiasp.Diasp.LoginException: 'NoneType' object has no attribute 'group'

```

Diasp.eu runs Diaspora 0.5.2.0-pb400f9f2

**Comment by fourier** [comment]
Thanks, I'll try to upgrade to 0.5 this weekend and fix this issue.

**Comment by schiessle** [comment]
This sounds great.... I'm really looking forward to it.

**Comment by fourier** [comment]
Ok, I've upgraded my pod to 0.5 and updated dependencies. I was able to reproduce the issue, now it is done. Please do

```
git update
git submodule update --init --recursive
```

**Comment by schiessle** [comment]
Thanks! In just tried it and it works now for me.

**Comment by fourier** [comment]
Glad it helped. Works on my pod for several days as well.
