### ISSUE TITLE
How to: Use Bot in Crontab

### ISSUE THREAD

**Issue by kaffeeringe** [fourier/rss-bot-diasp#3]
Hi!

How do I use this script in a cronjob? I added the path to the crontab variables and to bash. I can start the bot from any path now, but it fails if I am not in the right path:

```
Traceback (most recent call last):
  File "/home/pi/rss-bot-diasp/rss_bot.py", line 105, in <module>
    main()
  File "/home/pi/rss-bot-diasp/rss_bot.py", line 88, in main
    print "Not found bot named " + name
UnboundLocalError: local variable 'name' referenced before assignment
```

**Comment by fourier** [comment]
Hi,

I just add something like the following to the crontab of the diaspora user:

```
0 * * * * /home/diaspora/rss-bot-diasp/rss_bot.py --update GOG --db /home/diaspora/rss-bot-diasp/rss_bots.db
```
